export const FETCH_INIT = "FETCH_INIT";
export type FETCH_INIT = typeof FETCH_INIT;

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export type FETCH_SUCCESS = typeof FETCH_SUCCESS;

export const FETCH_FAILURE = "FETCH_FAILURE";
export type FETCH_FAILURE = typeof FETCH_FAILURE;

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export type TOGGLE_DRAWER = typeof TOGGLE_DRAWER;

export const TOGGLE_THEME = "TOGGLE_THEME";
export type TOGGLE_THEME = typeof TOGGLE_THEME;

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export type ADD_TO_FAVORITES = typeof ADD_TO_FAVORITES;

export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export type REMOVE_FROM_FAVORITES = typeof REMOVE_FROM_FAVORITES;

export const SET_LAST_LOCATION = "SET_LAST_LOCATION";
export type SET_LAST_LOCATION = typeof SET_LAST_LOCATION;
