export const FETCH_INIT = "FETCH_INIT";
export type FETCH_INIT = typeof FETCH_INIT;

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export type FETCH_SUCCESS = typeof FETCH_SUCCESS;

export const FETCH_FAILURE = "FETCH_FAILURE";
export type FETCH_FAILURE = typeof FETCH_FAILURE;

export const OPEN_DRAWER = "OPEN_DRAWER";
export type OPEN_DRAWER = typeof OPEN_DRAWER;

export const CLOSE_DRAWER = "CLOSE_DRAWER";
export type CLOSE_DRAWER = typeof CLOSE_DRAWER;

export const TURN_ON_DARK_THEME = "TURN_ON_DARK_THEME";
export type TURN_ON_DARK_THEME = typeof TURN_ON_DARK_THEME;

export const TURN_OFF_DARK_THEME = "TURN_OFF_DARK_THEME";
export type TURN_OFF_DARK_THEME = typeof TURN_OFF_DARK_THEME;

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export type ADD_TO_FAVORITES = typeof ADD_TO_FAVORITES;

export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export type REMOVE_FROM_FAVORITES = typeof REMOVE_FROM_FAVORITES;

export const SET_LAST_LOCATION = "SET_LAST_LOCATION";
export type SET_LAST_LOCATION = typeof SET_LAST_LOCATION;
